// Sumber tunggal data paket harga — dipakai oleh halaman depan (landing),
// halaman /pricing, dan halaman /register agar selalu sinkron.
export const PRICING_PLANS = {
  id: [
    {
      id: 'starter',
      name: 'Starter',
      price: 'Rp149.000',
      normalPrice: 'Rp199.000',
      period: '/ bulan',
      badge: 'Promo 2 bulan',
      description: 'Untuk UMKM dan bisnis kecil.',
      features: [
        'Analytics media sosial',
        'AI-powered insights',
        'Laporan performa',
        'Multi-platform analytics',
      ],
      button: 'Mulai dengan Starter',
    },
    {
      id: 'business',
      name: 'Business',
      price: 'Rp499.000',
      normalPrice: 'Rp699.000',
      period: '/ bulan',
      badge: 'Paling populer',
      popular: true,
      description: 'Untuk bisnis yang sedang berkembang.',
      features: [
        'Semua fitur Starter',
        'Analytics lebih lengkap',
        'AI-powered business insights',
        'Laporan performa berkala',
        'Multi-platform analytics',
      ],
      button: 'Mulai dengan Business',
    },
    {
      id: 'agency',
      name: 'Agency',
      price: 'Rp1.500.000',
      normalPrice: 'Rp2.500.000+',
      period: '/ bulan',
      badge: 'Untuk tim',
      description: 'Untuk agency dan organisasi dengan banyak akun dan anggota tim.',
      features: [
        'Semua fitur Business',
        'Multi-account management',
        'Advanced analytics',
        'Laporan untuk organisasi',
        'Dukungan prioritas',
      ],
      button: 'Mulai dengan Agency',
    },
  ],

  en: [
    {
      id: 'starter',
      name: 'Starter',
      price: '$10',
      normalPrice: '$15',
      period: '/ month',
      badge: '2-month promo',
      description: 'For small businesses and startups.',
      features: [
        'Social media analytics',
        'AI-powered insights',
        'Performance reports',
        'Multi-platform analytics',
      ],
      button: 'Start with Starter',
    },
    {
      id: 'business',
      name: 'Business',
      price: '$30',
      normalPrice: '$45',
      period: '/ month',
      badge: 'Most popular',
      popular: true,
      description: 'For growing businesses.',
      features: [
        'Everything in Starter',
        'Advanced analytics',
        'AI-powered business insights',
        'Regular performance reports',
        'Multi-platform analytics',
      ],
      button: 'Start with Business',
    },
    {
      id: 'agency',
      name: 'Agency',
      price: '$100',
      normalPrice: '$250+',
      period: '/ month',
      badge: 'Untuk tim',
      description: 'For agencies and organizations with many accounts and team members.',
      features: [
        'Everything in Business',
        'Multi-account management',
        'Advanced analytics',
        'Organization reports',
        'Priority support',
      ],
      button: 'Start with Agency',
    },
  ],
}
