-- Patch: pasang nilai default untuk kolom id pada public.users kalau belum ada.
-- Tabel yang dibuat manual lewat Table Editor kadang tidak otomatis diberi
-- default (gen_random_uuid() / identity), sehingga insert tanpa id eksplisit
-- gagal dengan "null value in column id violates not-null constraint".

create extension if not exists pgcrypto;

do $$
declare
  col_type text;
begin
  select data_type into col_type
  from information_schema.columns
  where table_schema = 'public' and table_name = 'users' and column_name = 'id';

  if col_type = 'uuid' then
    execute 'alter table public.users alter column id set default gen_random_uuid()';
  elsif col_type in ('bigint', 'integer', 'smallint') then
    execute 'alter table public.users alter column id add generated by default as identity';
  end if;
end $$;
